!/Assets/UniversalRenderPipelineGlobalSettings.asset
!/Assets/Scenes/SampleScene.unity
!/Assets/InputSystem_Actions.inputactions
!/Assets/Settings
!/Assets/Scenes
!/Assets/DefaultVolumeProfile.asset
UniversalRenderPipelineGlobalSettings.asset
Assets
SampleScene.unity
InputSystem_Actions.inputactions
Settings
Scenes
DefaultVolumeProfile.asset
